# fly.toml app configuration file generated for avalon-web on 2025-06-18T22:24:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avalon-web'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 4320
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  CONFIG_FILE_PATH = "app_data/avalon-config.yaml"

